// <auto-generated />
namespace PrincePortalWeb.Migrations.ProductsContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removetestfieldmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removetestfieldmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201807051832017_removetestfieldmigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
